name: l3build
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  l3build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12]
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get --fix-missing update
          sudo apt-get -y install ghostscript
        if: matrix.os == 'ubuntu-20.04'
      - uses: teatimeguest/setup-texlive-action@v2.6.2
        with:
          update-all-packages: true
          package-file: DEPENDS.txt
      - run: l3build ctan --show-log-on-error --halt-on-error
      - run: ./tests.pl
      - run: sed -i "s/0\.0\.0/$(date +%H.%M.%S)/g" build/distrib/tds/scripts/bibcop/bibcop.pl
      - run: sed -i "s/0000-00-00/$(date +%Y-%m-%d)/g" build/distrib/tds/scripts/bibcop/bibcop.pl
      - uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          folder: build/distrib/tds/tex/latex
          clean: true
        if: github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-20.04'
