name: l3build
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  l3build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - run: |
          sudo apt-get --fix-missing update
          sudo apt-get -y install ghostscript
        if: matrix.os == 'ubuntu-22.04'
      - uses: teatimeguest/setup-texlive-action@v3.1.0
        with:
          update-all-packages: true
          package-file: DEPENDS.txt
      - run: l3build ctan --show-log-on-error --halt-on-error
      - run: ./tests.pl
      - run: |
          mkdir build/gh-pages
          cp build/distrib/tds/scripts/bibcop/bibcop.pl build/gh-pages
          cp build/distrib/tds/tex/latex/bibcop/bibcop.sty build/gh-pages
          sed -i "s/0\.0\.0/$(date +%H.%M.%S)/g" build/gh-pages/bibcop.pl
          sed -i "s/0000-00-00/$(date +%Y-%m-%d)/g" build/gh-pages/bibcop.pl
          sed -i "s/0\.0\.0/$(date +%H.%M.%S)/g" build/gh-pages/bibcop.sty
          sed -i "s/0000-00-00/$(date +%Y-%m-%d)/g" build/gh-pages/bibcop.sty
        if: github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-22.04'
      - uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: build/gh-pages
          clean: true
        if: github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-22.04'
